<?xml version="1.0" encoding="utf-8"?><Database Name="QLQuanAn" Class="QLQuanAnDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=QLQuanAn;Persist Security Info=True;User ID=sa" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="QLQuanAnConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BanAn" Member="BanAns">
    <Type Name="BanAn">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ten" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="trangthai" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="BanAn_HoaDon" Member="HoaDons" ThisKey="id" OtherKey="idbanan" Type="HoaDon" />
    </Type>
  </Table>
  <Table Name="dbo.DanhMuc" Member="DanhMucs">
    <Type Name="DanhMuc">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ten" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="trangthai" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="DanhMuc_MonAn" Member="MonAns" ThisKey="id" OtherKey="iddanhmuc" Type="MonAn" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDon" Member="HoaDons">
    <Type Name="HoaDon">
      <Column Name="id" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ngayvao" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ngayra" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="idbanan" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="trangthai" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="giamgia" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tongtien" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="nguoitao" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="HoaDon_HoaDonChiTiet" Member="HoaDonChiTiets" ThisKey="id" OtherKey="idhoadon" Type="HoaDonChiTiet" />
      <Association Name="BanAn_HoaDon" Member="BanAn" ThisKey="idbanan" OtherKey="id" Type="BanAn" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDonChiTiet" Member="HoaDonChiTiets">
    <Type Name="HoaDonChiTiet">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idhoadon" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="idmonan" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="soluong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="HoaDon_HoaDonChiTiet" Member="HoaDon" ThisKey="idhoadon" OtherKey="id" Type="HoaDon" IsForeignKey="true" />
      <Association Name="MonAn_HoaDonChiTiet" Member="MonAn" ThisKey="idmonan" OtherKey="id" Type="MonAn" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TaiKhoan" Member="TaiKhoans">
    <Type Name="TaiKhoan">
      <Column Name="tendangnhap" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenhienthi" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="matkhau" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="loai" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MonAn" Member="MonAns">
    <Type Name="MonAn">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ten" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="iddanhmuc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="gia" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="trangthai" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="MonAn_HoaDonChiTiet" Member="HoaDonChiTiets" ThisKey="id" OtherKey="idmonan" Type="HoaDonChiTiet" />
      <Association Name="DanhMuc_MonAn" Member="DanhMuc" ThisKey="iddanhmuc" OtherKey="id" Type="DanhMuc" IsForeignKey="true" />
    </Type>
  </Table>
</Database>